### ISSUE TITLE
PharmaNet Revisions for Information Management Enhancements (PRIME) - Part II - Implementation

### ISSUE THREAD

**Issue by bcdevex** [bcgov/moh-prime#344]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/swu/opp-pharmanet-revisions-for-information-management-enhancements--prime----phase-2---implementation"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/swu/opp-pharmanet-revisions-for-information-management-enhancements--prime----phase-2---implementation">visit the opportunity page</a>.
The opportunity closes on <b>Thursday, February 20th, 2020 at 16:00 PST</b>.</p>

**Comment by rgreensp** [comment]
There are 4 "capabilities" listed as F/T for this opportunity and 4 additional required capabilities. What is the minimum number of resources that the province will accept for these capabilities in this opportunity?

**Comment by heidigiesbrecht** [comment]
> There are 4 "capabilities" listed as F/T for this opportunity and 4 additional required capabilities. What is the minimum number of resources that the province will accept for these capabilities in this opportunity?

Answer: The Province anticipates these capabilities will require a minimum of four F/T co-located resources working onsite with the Ministry team. Should additional resources be necessary, even in a P/T role, it is expected they will be working onsite during the majority of their allocated time with the Province.

**Comment by bcdevex** [comment]
This opportunity has been assigned
